version: "3.9"
services:
  db:
    image: mariadb:10.6
    container_name: glpi-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: glpi
      MYSQL_USER: glpi
      MYSQL_PASSWORD: glpi
    volumes:
      - db_data:/var/lib/mysql
  glpi:
    image: diouxx/glpi
    container_name: glpi-app
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      TIMEZONE: Africa/Casablanca
    volumes:
      - glpi_data:/var/www/html
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: glpi-phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: glpi-db
      MYSQL_USER: glpi
      MYSQL_PASSWORD: glpi
volumes:
  db_data:
  glpi_data: